name: Kang Commit

on:
  push:
    branches:
      - Pwd
      
  schedule:
    - cron: "* * * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Modify last update
        run: | 
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo "## ğŸ˜µ LAST UPDATED AT: ${d}" > update.md

      - name: Commit changes
        run: |
          git config --local user.email "arvinhpwd@gmail.com"
          git config --local user.name "ArvinHPWD"
          git add -A

          arr[0]="bot: ğŸ‘‹ Hello Dude!"
          arr[1]="bot: ğŸ¥³ Yuhhuuu!"
          arr[2]="bot: ğŸ˜¬ Working from Github."
          arr[3]="bot: ğŸ‘¨â€ğŸ’» Work, work, work!"
          arr[4]="bot: ğŸ˜ª Hufft..."
          arr[5]="bot: ğŸ˜ I'm working for my phone!"
          arr[6]="bot: ğŸ™„ Running task, again."
          arr[7]="bot: ğŸ‘» Thanks phone."

          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -am "${arr[$rand]} (at ${d})"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
